// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.DAL;

#nullable disable

namespace TestTask.DAL.Migrations
{
    [DbContext(typeof(TestTaskDbContext))]
    [Migration("20231210120019_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("804f84f1-1d81-4945-902d-ba4b03a11949"),
                            FullName = "Jane Austen"
                        },
                        new
                        {
                            Id = new Guid("8e1a4532-371d-4250-a8bb-3c1ac4dbae24"),
                            FullName = "Charles Dickens"
                        },
                        new
                        {
                            Id = new Guid("646c0730-218b-481e-94ad-7f4fc830cb70"),
                            FullName = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = new Guid("e64de713-3bd6-433b-9966-77c55485f9a1"),
                            FullName = "J.K. Rowling"
                        },
                        new
                        {
                            Id = new Guid("a84ef626-1ee3-41af-a57b-ac06cf18f862"),
                            FullName = "Agatha Christie"
                        },
                        new
                        {
                            Id = new Guid("f2ee12a7-b804-4e1a-be4d-7a273e0d7e1c"),
                            FullName = "George Orwell"
                        },
                        new
                        {
                            Id = new Guid("393a54fe-daa0-4bdb-8065-a182806681e6"),
                            FullName = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = new Guid("77b018b1-7811-48cf-b96c-32dcb226ad09"),
                            FullName = "William Shakespeare"
                        },
                        new
                        {
                            Id = new Guid("8cbb6105-89c5-4dca-8548-19376b5d3bf5"),
                            FullName = "Mark Twain"
                        },
                        new
                        {
                            Id = new Guid("370e4491-5633-4e78-9831-3c47ae4374b7"),
                            FullName = "Gabriel García Márquez"
                        },
                        new
                        {
                            Id = new Guid("f359606b-3297-4d1a-8360-a784d415c0e3"),
                            FullName = "Harper Lee"
                        },
                        new
                        {
                            Id = new Guid("d6c5a638-4312-417f-be34-671f55d8e4c6"),
                            FullName = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = new Guid("b9578ec3-d975-4966-9085-31819998bc84"),
                            FullName = "Homer"
                        },
                        new
                        {
                            Id = new Guid("a3aac870-20c5-4f1a-86dd-20be61665b84"),
                            FullName = "Stephen King"
                        },
                        new
                        {
                            Id = new Guid("844d2a69-2576-4f0b-acdd-d7b08fab436e"),
                            FullName = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = new Guid("b8ba024c-210b-4f77-898c-361c38c8ba9b"),
                            FullName = "Emily Brontë"
                        },
                        new
                        {
                            Id = new Guid("43a30ad7-1577-40da-bd2d-9aa5f7339546"),
                            FullName = "Virginia Woolf"
                        },
                        new
                        {
                            Id = new Guid("d3986608-7fa6-4c26-93e5-c522a3fd9cfa"),
                            FullName = "Charlotte Brontë"
                        },
                        new
                        {
                            Id = new Guid("352e3bd0-bdf8-49e1-9c29-a1a4f8ef3024"),
                            FullName = "Arthur Conan Doyle"
                        },
                        new
                        {
                            Id = new Guid("cbe43f46-9e76-48d6-a252-eeed33376e6c"),
                            FullName = "Ayn Rand"
                        },
                        new
                        {
                            Id = new Guid("c8a51eae-cc38-4c77-9bb6-4ec3ea8d620c"),
                            FullName = "Jane Goodall"
                        },
                        new
                        {
                            Id = new Guid("886e2b2b-466a-4453-90e8-cb33a617e249"),
                            FullName = "Michael Crichton"
                        },
                        new
                        {
                            Id = new Guid("fdce1659-c865-4693-bce3-c87cd59c56f5"),
                            FullName = "Isaac Asimov"
                        },
                        new
                        {
                            Id = new Guid("a6665d29-e292-468f-8fe2-1aa996d9ecac"),
                            FullName = "Margaret Atwood"
                        },
                        new
                        {
                            Id = new Guid("f96ab7a7-89e0-4324-a3bf-967f498caef3"),
                            FullName = "Kurt Vonnegut"
                        },
                        new
                        {
                            Id = new Guid("cef324de-ddfc-4d2a-81c6-55161436285c"),
                            FullName = "H.G. Wells"
                        },
                        new
                        {
                            Id = new Guid("32fa9aef-54a3-493f-9228-3dd20ebe95b4"),
                            FullName = "Roald Dahl"
                        },
                        new
                        {
                            Id = new Guid("a76eea22-9478-4b49-868f-12d2311c3492"),
                            FullName = "Hermann Hesse"
                        },
                        new
                        {
                            Id = new Guid("04cb0a64-f22a-47cf-b5fb-00c438e90d87"),
                            FullName = "Aldous Huxley"
                        },
                        new
                        {
                            Id = new Guid("37cce38c-e786-411a-9374-89d99efea101"),
                            FullName = "Toni Morrison"
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b71c2a5-c8fa-4446-b76f-f244880bd117"),
                            AuthorId = new Guid("c8a51eae-cc38-4c77-9bb6-4ec3ea8d620c"),
                            Description = "A timeless tale of love, manners, and societal expectations in Regency-era England by Jane Austen.",
                            ISBN = "978-0-14-143951-8",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("fa5bcbc6-a1f2-45ba-abcd-6958aac8fbb2"),
                            AuthorId = new Guid("b9578ec3-d975-4966-9085-31819998bc84"),
                            Description = "Harper Lee's powerful exploration of racial injustice and moral growth in the American South.",
                            ISBN = "978-0-06-112348-4",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("78dd080d-ac62-433f-a7e0-e502f4488568"),
                            AuthorId = new Guid("352e3bd0-bdf8-49e1-9c29-a1a4f8ef3024"),
                            Description = "George Orwell's dystopian masterpiece, depicting a nightmarish future under totalitarian rule.",
                            ISBN = "978-0-45-152493-5",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("aeda1fc4-5e5e-4fae-b377-466a32f0b93f"),
                            AuthorId = new Guid("c8a51eae-cc38-4c77-9bb6-4ec3ea8d620c"),
                            Description = "F. Scott Fitzgerald's classic portrayal of the American Dream, excess, and disillusionment in the Roaring Twenties.",
                            ISBN = "978-0-74-327356-5",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("a23bd7d5-50a6-4e54-be1b-ae8e598f309a"),
                            AuthorId = new Guid("cef324de-ddfc-4d2a-81c6-55161436285c"),
                            Description = "J.K. Rowling's enchanting introduction to the wizarding world, filled with magic, friendship, and adventure.",
                            ISBN = "978-0-59-035342-7",
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = new Guid("a3f16034-f110-4a27-b419-a3aa8afee6a4"),
                            AuthorId = new Guid("a84ef626-1ee3-41af-a57b-ac06cf18f862"),
                            ISBN = "978-0-54-792822-7",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("e295f6b0-ed22-4e19-9524-b1844ebf891e"),
                            AuthorId = new Guid("a3aac870-20c5-4f1a-86dd-20be61665b84"),
                            Description = "J.D. Salinger's iconic coming-of-age novel, capturing the angst and rebellion of a teenage boy in post-World War II America.",
                            ISBN = "978-0-31-676948-0",
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = new Guid("0f19acc6-80a1-4929-80eb-8559a851a275"),
                            AuthorId = new Guid("646c0730-218b-481e-94ad-7f4fc830cb70"),
                            Description = "Leo Tolstoy's epic portrayal of Russian society during the Napoleonic Wars, blending history, philosophy, and human drama.",
                            ISBN = "978-0-14-303500-8",
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = new Guid("ae94d435-31b7-44c7-ba5e-53b18f1e6afe"),
                            AuthorId = new Guid("f96ab7a7-89e0-4324-a3bf-967f498caef3"),
                            Description = "Homer's ancient Greek epic, recounting the adventures of Odysseus as he journeys home from the Trojan War.",
                            ISBN = "978-0-14-303995-2",
                            Title = "The Odyssey"
                        },
                        new
                        {
                            Id = new Guid("02e8f4c3-f031-451e-9d57-bc9cd8f4dcf9"),
                            AuthorId = new Guid("fdce1659-c865-4693-bce3-c87cd59c56f5"),
                            ISBN = "978-0-06-085052-4",
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = new Guid("037e8836-8448-4a65-a439-99804aef6b13"),
                            AuthorId = new Guid("fdce1659-c865-4693-bce3-c87cd59c56f5"),
                            Description = "J.R.R. Tolkien's epic fantasy trilogy, featuring the quest to destroy the One Ring and save Middle-earth from the dark forces of Sauron.",
                            ISBN = "978-0-54-400341-5",
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("1848d0e1-f073-47d1-afbc-36543210d616"),
                            AuthorId = new Guid("d3986608-7fa6-4c26-93e5-c522a3fd9cfa"),
                            Description = "Mary Shelley's gothic tale of scientific hubris and the consequences of creating life.",
                            ISBN = "978-0-48-628211-4",
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = new Guid("5c82cfc3-79a8-4079-ba51-4049bad1dd10"),
                            AuthorId = new Guid("886e2b2b-466a-4453-90e8-cb33a617e249"),
                            Description = "Fyodor Dostoevsky's psychological thriller, exploring the moral and psychological turmoil of a young man in St. Petersburg.",
                            ISBN = "978-0-14-310763-7",
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = new Guid("8cb4d66a-7f6a-4423-a26d-c1dca8bc92bb"),
                            AuthorId = new Guid("370e4491-5633-4e78-9831-3c47ae4374b7"),
                            ISBN = "978-0-06-112028-4",
                            Title = "One Hundred Years of Solitude"
                        },
                        new
                        {
                            Id = new Guid("036bdc1d-fe5a-468e-9b62-f86c40863bd1"),
                            AuthorId = new Guid("d3986608-7fa6-4c26-93e5-c522a3fd9cfa"),
                            Description = "C.S. Lewis's beloved fantasy series, taking readers to the enchanting land of Narnia and its magical inhabitants.",
                            ISBN = "978-0-06-112008-4",
                            Title = "The Chronicles of Narnia"
                        },
                        new
                        {
                            Id = new Guid("4b3a7c87-897e-4e8b-9b55-b268d0d65602"),
                            AuthorId = new Guid("8cbb6105-89c5-4dca-8548-19376b5d3bf5"),
                            Description = "Douglas Adams's hilarious space adventure, following the misadventures of Arthur Dent and his extraterrestrial friend Ford Prefect.",
                            ISBN = "978-0-34-539180-3",
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = new Guid("d203b227-620e-4a71-bde5-8ef6219c6e2d"),
                            AuthorId = new Guid("cef324de-ddfc-4d2a-81c6-55161436285c"),
                            Description = "Stephen King's chilling tale of supernatural horror, isolation, and the descent into madness at the haunted Overlook Hotel.",
                            ISBN = "978-0-38-511683-7",
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = new Guid("fe633b05-cebe-4370-bd19-09100c0b7344"),
                            AuthorId = new Guid("844d2a69-2576-4f0b-acdd-d7b08fab436e"),
                            Description = "Herman Melville's epic journey aboard the whaling ship Pequod, driven by Captain Ahab's obsessive quest for the white whale.",
                            ISBN = "978-0-14-310635-7",
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            Id = new Guid("dd848273-7c2f-423e-9c5f-0982db7eaa9c"),
                            AuthorId = new Guid("e64de713-3bd6-433b-9966-77c55485f9a1"),
                            ISBN = "978-0-19-921613-3",
                            Title = "Alice's Adventures in Wonderland"
                        },
                        new
                        {
                            Id = new Guid("6506e3bf-7adf-487a-85cd-9ddf2571b86d"),
                            AuthorId = new Guid("d3986608-7fa6-4c26-93e5-c522a3fd9cfa"),
                            Description = "Stieg Larsson's gripping mystery featuring investigative journalist Mikael Blomkvist and the enigmatic hacker Lisbeth Salander.",
                            ISBN = "978-0-30-726975-1",
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            Id = new Guid("530ab3f8-6c5b-4659-828a-803f5f482274"),
                            AuthorId = new Guid("8cbb6105-89c5-4dca-8548-19376b5d3bf5"),
                            Description = "Suzanne Collins's dystopian saga of Katniss Everdeen's fight for survival in the annual Hunger Games.",
                            ISBN = "978-0-43-902352-8",
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            Id = new Guid("da307696-1a69-446d-a218-8fce5197ce47"),
                            AuthorId = new Guid("886e2b2b-466a-4453-90e8-cb33a617e249"),
                            Description = "Frank Herbert's science fiction epic set in a distant future where noble houses vie for control of the desert planet Arrakis and its valuable spice melange.",
                            ISBN = "978-0-44-117271-9",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = new Guid("8a9384a4-2c40-47f7-a2c1-5b69fd054c1d"),
                            AuthorId = new Guid("370e4491-5633-4e78-9831-3c47ae4374b7"),
                            Description = "Fyodor Dostoevsky's exploration of morality, faith, and family dynamics through the complex relationships of the Karamazov brothers.",
                            ISBN = "978-0-14-044924-2",
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            Id = new Guid("d7e77f30-934e-4d7b-93e5-0ea110092719"),
                            AuthorId = new Guid("a84ef626-1ee3-41af-a57b-ac06cf18f862"),
                            ISBN = "978-0-14-143955-6",
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            Id = new Guid("0c745d6c-9d08-4176-a06b-2ccefe95b587"),
                            AuthorId = new Guid("352e3bd0-bdf8-49e1-9c29-a1a4f8ef3024"),
                            Description = "Geoffrey Chaucer's collection of stories told by a diverse group of pilgrims on their journey to Canterbury.",
                            ISBN = "978-0-14-042234-4",
                            Title = "The Canterbury Tales"
                        },
                        new
                        {
                            Id = new Guid("3aa1c312-1e6c-4179-9d52-ce6e1299cb86"),
                            AuthorId = new Guid("a3aac870-20c5-4f1a-86dd-20be61665b84"),
                            ISBN = "978-0-14-143957-0",
                            Title = "The Picture of Dorian Gray"
                        },
                        new
                        {
                            Id = new Guid("4951bfc0-816a-4541-adaa-d13a75c365f0"),
                            AuthorId = new Guid("844d2a69-2576-4f0b-acdd-d7b08fab436e"),
                            Description = "Paulo Coelho's philosophical novel about Santiago, a shepherd boy, on a journey to discover his personal legend.",
                            ISBN = "978-0-06-112241-5",
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = new Guid("6a57c572-dc3e-497d-b414-7944663ab7df"),
                            AuthorId = new Guid("77b018b1-7811-48cf-b96c-32dcb226ad09"),
                            Description = "Margaret Atwood's dystopian novel set in the Republic of Gilead, where women's rights are severely restricted.",
                            ISBN = "978-0-38-549081-8",
                            Title = "The Handmaid's Tale"
                        },
                        new
                        {
                            Id = new Guid("dd6562b3-93d7-45bf-894f-7d00c7897237"),
                            AuthorId = new Guid("a76eea22-9478-4b49-868f-12d2311c3492"),
                            Description = "Cormac McCarthy's post-apocalyptic tale of a father and son's harrowing journey through a desolate landscape.",
                            ISBN = "978-0-30-738789-9",
                            Title = "The Road"
                        },
                        new
                        {
                            Id = new Guid("037fec9e-827f-45b7-89bf-e9bbff837d38"),
                            AuthorId = new Guid("844d2a69-2576-4f0b-acdd-d7b08fab436e"),
                            Description = "Alexandre Dumas's classic adventure novel of betrayal, revenge, and redemption.",
                            ISBN = "978-0-14-044926-6",
                            Title = "The Count of Monte Cristo"
                        },
                        new
                        {
                            Id = new Guid("e729b54e-4f90-47d7-9c58-8b95ea089a4a"),
                            AuthorId = new Guid("b8ba024c-210b-4f77-898c-361c38c8ba9b"),
                            ISBN = "978-0-45-141943-9",
                            Title = "Les Misérables"
                        },
                        new
                        {
                            Id = new Guid("476bf9e1-2ef7-4f4e-aedb-096d75007cc5"),
                            AuthorId = new Guid("8e1a4532-371d-4250-a8bb-3c1ac4dbae24"),
                            Description = "Joseph Heller's satirical novel depicting the absurdities and paradoxes of war.",
                            ISBN = "978-0-68-484121-9",
                            Title = "The Catch-22"
                        },
                        new
                        {
                            Id = new Guid("2cf3063b-e92e-4d4c-a8a9-281423e349fd"),
                            AuthorId = new Guid("f2ee12a7-b804-4e1a-be4d-7a273e0d7e1c"),
                            ISBN = "978-0-15-602835-6",
                            Title = "The Color Purple"
                        },
                        new
                        {
                            Id = new Guid("df63308a-4335-4f69-a74c-051993261fcb"),
                            AuthorId = new Guid("646c0730-218b-481e-94ad-7f4fc830cb70"),
                            Description = "Ken Kesey's classic novel set in a mental hospital, challenging authority and celebrating individuality.",
                            ISBN = "978-0-45-116396-7",
                            Title = "One Flew Over the Cuckoo's Nest"
                        },
                        new
                        {
                            Id = new Guid("6dbd3ee6-d9ce-42df-986a-8b0007f28f96"),
                            AuthorId = new Guid("fdce1659-c865-4693-bce3-c87cd59c56f5"),
                            Description = "Andy Weir's gripping science fiction novel about an astronaut stranded on Mars and his fight for survival.",
                            ISBN = "978-0-55-341802-6",
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = new Guid("d6facd73-57cd-4382-a31e-3995353ff91e"),
                            AuthorId = new Guid("646c0730-218b-481e-94ad-7f4fc830cb70"),
                            Description = "Khaled Hosseini's powerful novel about friendship, betrayal, and redemption in Afghanistan.",
                            ISBN = "978-1-59-463193-1",
                            Title = "The Kite Runner"
                        },
                        new
                        {
                            Id = new Guid("5ba511c5-bcf6-4adb-ba15-83dc32354b8c"),
                            AuthorId = new Guid("646c0730-218b-481e-94ad-7f4fc830cb70"),
                            ISBN = "978-1-25-030169-7",
                            Title = "The Silent Patient"
                        },
                        new
                        {
                            Id = new Guid("10606543-0d01-4ac0-b6b5-691bcafe3c30"),
                            AuthorId = new Guid("804f84f1-1d81-4945-902d-ba4b03a11949"),
                            Description = "Tara Westover's memoir recounting her journey from a rural Idaho childhood to gaining an education against all odds.",
                            ISBN = "978-0-52-558019-4",
                            Title = "Educated"
                        },
                        new
                        {
                            Id = new Guid("7f788719-b041-446a-a264-7f861248655a"),
                            AuthorId = new Guid("a76eea22-9478-4b49-868f-12d2311c3492"),
                            Description = "Yuval Noah Harari's exploration of the history and impact of Homo sapiens on the world.",
                            ISBN = "978-0-99-711060-8",
                            Title = "Sapiens: A Brief History of Humankind"
                        },
                        new
                        {
                            Id = new Guid("cfb4956c-43fb-4b1b-a430-28a65746b1cd"),
                            AuthorId = new Guid("32fa9aef-54a3-493f-9228-3dd20ebe95b4"),
                            Description = "Donna Tartt's Pulitzer Prize-winning novel about a young boy's life after a terrorist attack in a New York art museum.",
                            ISBN = "978-0-31-605543-7",
                            Title = "The Goldfinch"
                        },
                        new
                        {
                            Id = new Guid("24a8866e-827a-4324-9b9c-62cdf0219945"),
                            AuthorId = new Guid("a84ef626-1ee3-41af-a57b-ac06cf18f862"),
                            Description = "Erin Morgenstern's magical tale of a mysterious competition between two illusionists in a magical circus.",
                            ISBN = "978-0-38-553970-6",
                            Title = "The Night Circus"
                        },
                        new
                        {
                            Id = new Guid("4955bb49-bf12-463a-8cb4-e0d0b396d332"),
                            AuthorId = new Guid("646c0730-218b-481e-94ad-7f4fc830cb70"),
                            Description = "Rebecca Skloot's biography exploring the life and legacy of Henrietta Lacks, whose cells were used for medical research without her knowledge.",
                            ISBN = "978-1-40-005217-2",
                            Title = "The Immortal Life of Henrietta Lacks"
                        },
                        new
                        {
                            Id = new Guid("3c2b33e0-d08c-4306-aa43-75459237deb3"),
                            AuthorId = new Guid("b8ba024c-210b-4f77-898c-361c38c8ba9b"),
                            Description = "John Green's heart-wrenching novel about two teenagers with cancer who fall in love.",
                            ISBN = "978-0-14-242417-9",
                            Title = "The Fault in Our Stars"
                        },
                        new
                        {
                            Id = new Guid("e3959340-6a6e-45f5-a75d-3741be5f9951"),
                            AuthorId = new Guid("cef324de-ddfc-4d2a-81c6-55161436285c"),
                            Description = "M. Scott Peck's exploration of personal growth, love, and spiritual development.",
                            ISBN = "978-0-74-324315-8",
                            Title = "The Road Less Traveled"
                        },
                        new
                        {
                            Id = new Guid("e4543b2c-6472-46b6-836c-68839f50a9d9"),
                            AuthorId = new Guid("8e1a4532-371d-4250-a8bb-3c1ac4dbae24"),
                            Description = "Paula Hawkins's psychological thriller about a woman who becomes entangled in a missing person investigation.",
                            ISBN = "978-1-59-463402-4",
                            Title = "The Girl on the Train"
                        },
                        new
                        {
                            Id = new Guid("8725a3db-2f1a-409e-ad30-6cba94531ae2"),
                            AuthorId = new Guid("a76eea22-9478-4b49-868f-12d2311c3492"),
                            Description = "Dan Brown's gripping mystery involving symbology, art, and secret societies.",
                            ISBN = "978-0-30-747427-8",
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = new Guid("0e9ed85f-a740-4650-b1c8-fc18d7969768"),
                            AuthorId = new Guid("32fa9aef-54a3-493f-9228-3dd20ebe95b4"),
                            Description = "Kathryn Stockett's novel about African American maids working in white households in Jackson, Mississippi, during the early 1960s.",
                            ISBN = "978-0-42-523220-0",
                            Title = "The Help"
                        },
                        new
                        {
                            Id = new Guid("d898a657-04bd-4d2e-a9c9-330ce533e413"),
                            AuthorId = new Guid("fdce1659-c865-4693-bce3-c87cd59c56f5"),
                            ISBN = "978-0-14-044022-5",
                            Title = "The Three Musketeers"
                        },
                        new
                        {
                            Id = new Guid("97d2692c-db28-478f-a5f9-1e55798b9bbf"),
                            AuthorId = new Guid("cef324de-ddfc-4d2a-81c6-55161436285c"),
                            Description = "Haruki Murakami's surreal and mesmerizing novel exploring the mysteries of human consciousness.",
                            ISBN = "978-0-67-977543-0",
                            Title = "The Wind-Up Bird Chronicle"
                        },
                        new
                        {
                            Id = new Guid("33bbb4b8-b362-4e69-aaba-a2d588ae02b3"),
                            AuthorId = new Guid("f359606b-3297-4d1a-8360-a784d415c0e3"),
                            ISBN = "978-0-37-584220-7",
                            Title = "The Book Thief"
                        },
                        new
                        {
                            Id = new Guid("369d6a60-c748-4526-aa5b-961b3d7a80fe"),
                            AuthorId = new Guid("a6665d29-e292-468f-8fe2-1aa996d9ecac"),
                            Description = "Amy Tan's novel exploring the relationships between Chinese-American immigrant mothers and their American-born daughters.",
                            ISBN = "978-0-80-417839-9",
                            Title = "The Joy Luck Club"
                        },
                        new
                        {
                            Id = new Guid("12f83231-03b4-4ebb-bb24-340c84263253"),
                            AuthorId = new Guid("04cb0a64-f22a-47cf-b5fb-00c438e90d87"),
                            Description = "John Steinbeck's novel depicting the struggles of a displaced Oklahoma family during the Great Depression.",
                            ISBN = "978-0-14-303943-3",
                            Title = "The Grapes of Wrath"
                        },
                        new
                        {
                            Id = new Guid("9e2d481b-874f-4587-a842-072098955bcb"),
                            AuthorId = new Guid("c8a51eae-cc38-4c77-9bb6-4ec3ea8d620c"),
                            Description = "Charles Duhigg's exploration of the science behind habits and how they can be transformed.",
                            ISBN = "978-0-81-298160-5",
                            Title = "The Power of Habit"
                        },
                        new
                        {
                            Id = new Guid("9a147065-60a7-453b-b3ae-80bc4b4156d9"),
                            AuthorId = new Guid("886e2b2b-466a-4453-90e8-cb33a617e249"),
                            ISBN = "978-0-14-200174-5",
                            Title = "The Secret Life of Bees"
                        },
                        new
                        {
                            Id = new Guid("bbf49d78-4fc9-4b0d-8e8e-7ca5e72a03c8"),
                            AuthorId = new Guid("886e2b2b-466a-4453-90e8-cb33a617e249"),
                            ISBN = "978-0-52-551488-0",
                            Title = "The Immortalists"
                        },
                        new
                        {
                            Id = new Guid("0ec261fb-35e3-402b-b4d0-c30ecb4a34eb"),
                            AuthorId = new Guid("a3aac870-20c5-4f1a-86dd-20be61665b84"),
                            Description = "Jeannette Walls's memoir detailing her unconventional and often troubled childhood.",
                            ISBN = "978-0-74-324754-5",
                            Title = "The Glass Castle"
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BookGenre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenreId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BooksGenres");

                    b.HasData(
                        new
                        {
                            GenreId = new Guid("234e659d-7919-4a3a-8e6c-8a6b58c7dae4"),
                            BookId = new Guid("6b71c2a5-c8fa-4446-b76f-f244880bd117")
                        },
                        new
                        {
                            GenreId = new Guid("89fa23ba-749b-460b-9882-f3cbbd76a1cd"),
                            BookId = new Guid("6b71c2a5-c8fa-4446-b76f-f244880bd117")
                        },
                        new
                        {
                            GenreId = new Guid("09c11eca-5c58-465d-92fc-6891e2c6cf49"),
                            BookId = new Guid("fa5bcbc6-a1f2-45ba-abcd-6958aac8fbb2")
                        },
                        new
                        {
                            GenreId = new Guid("d6fbd6be-632f-4f0d-b2f2-1776e1f068e1"),
                            BookId = new Guid("fa5bcbc6-a1f2-45ba-abcd-6958aac8fbb2")
                        },
                        new
                        {
                            GenreId = new Guid("8cb9facc-e26e-4ce2-8765-f7a3a291f955"),
                            BookId = new Guid("fa5bcbc6-a1f2-45ba-abcd-6958aac8fbb2")
                        },
                        new
                        {
                            GenreId = new Guid("35140fdb-06f1-4edb-be27-b02a1a44d91f"),
                            BookId = new Guid("78dd080d-ac62-433f-a7e0-e502f4488568")
                        },
                        new
                        {
                            GenreId = new Guid("09c11eca-5c58-465d-92fc-6891e2c6cf49"),
                            BookId = new Guid("aeda1fc4-5e5e-4fae-b377-466a32f0b93f")
                        },
                        new
                        {
                            GenreId = new Guid("234e659d-7919-4a3a-8e6c-8a6b58c7dae4"),
                            BookId = new Guid("a23bd7d5-50a6-4e54-be1b-ae8e598f309a")
                        },
                        new
                        {
                            GenreId = new Guid("3a42bd69-50f4-49cc-9184-55d97bc930d4"),
                            BookId = new Guid("a23bd7d5-50a6-4e54-be1b-ae8e598f309a")
                        },
                        new
                        {
                            GenreId = new Guid("d6fbd6be-632f-4f0d-b2f2-1776e1f068e1"),
                            BookId = new Guid("a3f16034-f110-4a27-b419-a3aa8afee6a4")
                        },
                        new
                        {
                            GenreId = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            BookId = new Guid("a3f16034-f110-4a27-b419-a3aa8afee6a4")
                        },
                        new
                        {
                            GenreId = new Guid("291470b7-2128-447f-ab64-8f82770c74a2"),
                            BookId = new Guid("e295f6b0-ed22-4e19-9524-b1844ebf891e")
                        },
                        new
                        {
                            GenreId = new Guid("d47c0cf6-5484-4b59-8426-9d8f2e34812d"),
                            BookId = new Guid("e295f6b0-ed22-4e19-9524-b1844ebf891e")
                        },
                        new
                        {
                            GenreId = new Guid("234e659d-7919-4a3a-8e6c-8a6b58c7dae4"),
                            BookId = new Guid("0f19acc6-80a1-4929-80eb-8559a851a275")
                        },
                        new
                        {
                            GenreId = new Guid("35140fdb-06f1-4edb-be27-b02a1a44d91f"),
                            BookId = new Guid("ae94d435-31b7-44c7-ba5e-53b18f1e6afe")
                        },
                        new
                        {
                            GenreId = new Guid("89fa23ba-749b-460b-9882-f3cbbd76a1cd"),
                            BookId = new Guid("ae94d435-31b7-44c7-ba5e-53b18f1e6afe")
                        },
                        new
                        {
                            GenreId = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            BookId = new Guid("ae94d435-31b7-44c7-ba5e-53b18f1e6afe")
                        },
                        new
                        {
                            GenreId = new Guid("f8e30203-770d-458f-856b-427734a58afc"),
                            BookId = new Guid("02e8f4c3-f031-451e-9d57-bc9cd8f4dcf9")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("02e8f4c3-f031-451e-9d57-bc9cd8f4dcf9")
                        },
                        new
                        {
                            GenreId = new Guid("0e3ce01e-df95-451f-a59d-8774501c6bef"),
                            BookId = new Guid("037e8836-8448-4a65-a439-99804aef6b13")
                        },
                        new
                        {
                            GenreId = new Guid("2c26cd80-e2e9-480a-8ce2-089e4545e01b"),
                            BookId = new Guid("037e8836-8448-4a65-a439-99804aef6b13")
                        },
                        new
                        {
                            GenreId = new Guid("d47c0cf6-5484-4b59-8426-9d8f2e34812d"),
                            BookId = new Guid("037e8836-8448-4a65-a439-99804aef6b13")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("037e8836-8448-4a65-a439-99804aef6b13")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("1848d0e1-f073-47d1-afbc-36543210d616")
                        },
                        new
                        {
                            GenreId = new Guid("f8e30203-770d-458f-856b-427734a58afc"),
                            BookId = new Guid("1848d0e1-f073-47d1-afbc-36543210d616")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("5c82cfc3-79a8-4079-ba51-4049bad1dd10")
                        },
                        new
                        {
                            GenreId = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            BookId = new Guid("5c82cfc3-79a8-4079-ba51-4049bad1dd10")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("8cb4d66a-7f6a-4423-a26d-c1dca8bc92bb")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("8cb4d66a-7f6a-4423-a26d-c1dca8bc92bb")
                        },
                        new
                        {
                            GenreId = new Guid("f8e30203-770d-458f-856b-427734a58afc"),
                            BookId = new Guid("8cb4d66a-7f6a-4423-a26d-c1dca8bc92bb")
                        },
                        new
                        {
                            GenreId = new Guid("64bc61c1-7a4c-4844-bc02-17ab6b5ae64d"),
                            BookId = new Guid("036bdc1d-fe5a-468e-9b62-f86c40863bd1")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("4b3a7c87-897e-4e8b-9b55-b268d0d65602")
                        },
                        new
                        {
                            GenreId = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            BookId = new Guid("4b3a7c87-897e-4e8b-9b55-b268d0d65602")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("d203b227-620e-4a71-bde5-8ef6219c6e2d")
                        },
                        new
                        {
                            GenreId = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            BookId = new Guid("d203b227-620e-4a71-bde5-8ef6219c6e2d")
                        },
                        new
                        {
                            GenreId = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            BookId = new Guid("d203b227-620e-4a71-bde5-8ef6219c6e2d")
                        },
                        new
                        {
                            GenreId = new Guid("3a42bd69-50f4-49cc-9184-55d97bc930d4"),
                            BookId = new Guid("fe633b05-cebe-4370-bd19-09100c0b7344")
                        },
                        new
                        {
                            GenreId = new Guid("64bc61c1-7a4c-4844-bc02-17ab6b5ae64d"),
                            BookId = new Guid("dd848273-7c2f-423e-9c5f-0982db7eaa9c")
                        },
                        new
                        {
                            GenreId = new Guid("234e659d-7919-4a3a-8e6c-8a6b58c7dae4"),
                            BookId = new Guid("dd848273-7c2f-423e-9c5f-0982db7eaa9c")
                        },
                        new
                        {
                            GenreId = new Guid("09c11eca-5c58-465d-92fc-6891e2c6cf49"),
                            BookId = new Guid("dd848273-7c2f-423e-9c5f-0982db7eaa9c")
                        },
                        new
                        {
                            GenreId = new Guid("2c26cd80-e2e9-480a-8ce2-089e4545e01b"),
                            BookId = new Guid("6506e3bf-7adf-487a-85cd-9ddf2571b86d")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("530ab3f8-6c5b-4659-828a-803f5f482274")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("530ab3f8-6c5b-4659-828a-803f5f482274")
                        },
                        new
                        {
                            GenreId = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            BookId = new Guid("530ab3f8-6c5b-4659-828a-803f5f482274")
                        },
                        new
                        {
                            GenreId = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            BookId = new Guid("da307696-1a69-446d-a218-8fce5197ce47")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("da307696-1a69-446d-a218-8fce5197ce47")
                        },
                        new
                        {
                            GenreId = new Guid("2c26cd80-e2e9-480a-8ce2-089e4545e01b"),
                            BookId = new Guid("da307696-1a69-446d-a218-8fce5197ce47")
                        },
                        new
                        {
                            GenreId = new Guid("0e3ce01e-df95-451f-a59d-8774501c6bef"),
                            BookId = new Guid("8a9384a4-2c40-47f7-a2c1-5b69fd054c1d")
                        },
                        new
                        {
                            GenreId = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            BookId = new Guid("8a9384a4-2c40-47f7-a2c1-5b69fd054c1d")
                        },
                        new
                        {
                            GenreId = new Guid("89fa23ba-749b-460b-9882-f3cbbd76a1cd"),
                            BookId = new Guid("8a9384a4-2c40-47f7-a2c1-5b69fd054c1d")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("d7e77f30-934e-4d7b-93e5-0ea110092719")
                        },
                        new
                        {
                            GenreId = new Guid("09c11eca-5c58-465d-92fc-6891e2c6cf49"),
                            BookId = new Guid("d7e77f30-934e-4d7b-93e5-0ea110092719")
                        },
                        new
                        {
                            GenreId = new Guid("89fa23ba-749b-460b-9882-f3cbbd76a1cd"),
                            BookId = new Guid("d7e77f30-934e-4d7b-93e5-0ea110092719")
                        },
                        new
                        {
                            GenreId = new Guid("234e659d-7919-4a3a-8e6c-8a6b58c7dae4"),
                            BookId = new Guid("0c745d6c-9d08-4176-a06b-2ccefe95b587")
                        },
                        new
                        {
                            GenreId = new Guid("f8e30203-770d-458f-856b-427734a58afc"),
                            BookId = new Guid("0c745d6c-9d08-4176-a06b-2ccefe95b587")
                        },
                        new
                        {
                            GenreId = new Guid("d47c0cf6-5484-4b59-8426-9d8f2e34812d"),
                            BookId = new Guid("0c745d6c-9d08-4176-a06b-2ccefe95b587")
                        },
                        new
                        {
                            GenreId = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            BookId = new Guid("3aa1c312-1e6c-4179-9d52-ce6e1299cb86")
                        },
                        new
                        {
                            GenreId = new Guid("291470b7-2128-447f-ab64-8f82770c74a2"),
                            BookId = new Guid("3aa1c312-1e6c-4179-9d52-ce6e1299cb86")
                        },
                        new
                        {
                            GenreId = new Guid("64bc61c1-7a4c-4844-bc02-17ab6b5ae64d"),
                            BookId = new Guid("4951bfc0-816a-4541-adaa-d13a75c365f0")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("4951bfc0-816a-4541-adaa-d13a75c365f0")
                        },
                        new
                        {
                            GenreId = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            BookId = new Guid("4951bfc0-816a-4541-adaa-d13a75c365f0")
                        },
                        new
                        {
                            GenreId = new Guid("8cb9facc-e26e-4ce2-8765-f7a3a291f955"),
                            BookId = new Guid("6a57c572-dc3e-497d-b414-7944663ab7df")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("6a57c572-dc3e-497d-b414-7944663ab7df")
                        },
                        new
                        {
                            GenreId = new Guid("291470b7-2128-447f-ab64-8f82770c74a2"),
                            BookId = new Guid("dd6562b3-93d7-45bf-894f-7d00c7897237")
                        },
                        new
                        {
                            GenreId = new Guid("0e3ce01e-df95-451f-a59d-8774501c6bef"),
                            BookId = new Guid("dd6562b3-93d7-45bf-894f-7d00c7897237")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("037fec9e-827f-45b7-89bf-e9bbff837d38")
                        },
                        new
                        {
                            GenreId = new Guid("35140fdb-06f1-4edb-be27-b02a1a44d91f"),
                            BookId = new Guid("037fec9e-827f-45b7-89bf-e9bbff837d38")
                        },
                        new
                        {
                            GenreId = new Guid("8cb9facc-e26e-4ce2-8765-f7a3a291f955"),
                            BookId = new Guid("037fec9e-827f-45b7-89bf-e9bbff837d38")
                        },
                        new
                        {
                            GenreId = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            BookId = new Guid("e729b54e-4f90-47d7-9c58-8b95ea089a4a")
                        },
                        new
                        {
                            GenreId = new Guid("234e659d-7919-4a3a-8e6c-8a6b58c7dae4"),
                            BookId = new Guid("e729b54e-4f90-47d7-9c58-8b95ea089a4a")
                        },
                        new
                        {
                            GenreId = new Guid("2c26cd80-e2e9-480a-8ce2-089e4545e01b"),
                            BookId = new Guid("e729b54e-4f90-47d7-9c58-8b95ea089a4a")
                        },
                        new
                        {
                            GenreId = new Guid("35140fdb-06f1-4edb-be27-b02a1a44d91f"),
                            BookId = new Guid("476bf9e1-2ef7-4f4e-aedb-096d75007cc5")
                        },
                        new
                        {
                            GenreId = new Guid("8cb9facc-e26e-4ce2-8765-f7a3a291f955"),
                            BookId = new Guid("476bf9e1-2ef7-4f4e-aedb-096d75007cc5")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("2cf3063b-e92e-4d4c-a8a9-281423e349fd")
                        },
                        new
                        {
                            GenreId = new Guid("3a42bd69-50f4-49cc-9184-55d97bc930d4"),
                            BookId = new Guid("2cf3063b-e92e-4d4c-a8a9-281423e349fd")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("df63308a-4335-4f69-a74c-051993261fcb")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("df63308a-4335-4f69-a74c-051993261fcb")
                        },
                        new
                        {
                            GenreId = new Guid("234e659d-7919-4a3a-8e6c-8a6b58c7dae4"),
                            BookId = new Guid("df63308a-4335-4f69-a74c-051993261fcb")
                        },
                        new
                        {
                            GenreId = new Guid("35140fdb-06f1-4edb-be27-b02a1a44d91f"),
                            BookId = new Guid("6dbd3ee6-d9ce-42df-986a-8b0007f28f96")
                        },
                        new
                        {
                            GenreId = new Guid("8cb9facc-e26e-4ce2-8765-f7a3a291f955"),
                            BookId = new Guid("6dbd3ee6-d9ce-42df-986a-8b0007f28f96")
                        },
                        new
                        {
                            GenreId = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            BookId = new Guid("d6facd73-57cd-4382-a31e-3995353ff91e")
                        },
                        new
                        {
                            GenreId = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            BookId = new Guid("d6facd73-57cd-4382-a31e-3995353ff91e")
                        },
                        new
                        {
                            GenreId = new Guid("3a42bd69-50f4-49cc-9184-55d97bc930d4"),
                            BookId = new Guid("d6facd73-57cd-4382-a31e-3995353ff91e")
                        },
                        new
                        {
                            GenreId = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            BookId = new Guid("5ba511c5-bcf6-4adb-ba15-83dc32354b8c")
                        },
                        new
                        {
                            GenreId = new Guid("2c26cd80-e2e9-480a-8ce2-089e4545e01b"),
                            BookId = new Guid("5ba511c5-bcf6-4adb-ba15-83dc32354b8c")
                        },
                        new
                        {
                            GenreId = new Guid("d47c0cf6-5484-4b59-8426-9d8f2e34812d"),
                            BookId = new Guid("10606543-0d01-4ac0-b6b5-691bcafe3c30")
                        },
                        new
                        {
                            GenreId = new Guid("09c11eca-5c58-465d-92fc-6891e2c6cf49"),
                            BookId = new Guid("7f788719-b041-446a-a264-7f861248655a")
                        },
                        new
                        {
                            GenreId = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            BookId = new Guid("7f788719-b041-446a-a264-7f861248655a")
                        },
                        new
                        {
                            GenreId = new Guid("3a42bd69-50f4-49cc-9184-55d97bc930d4"),
                            BookId = new Guid("7f788719-b041-446a-a264-7f861248655a")
                        },
                        new
                        {
                            GenreId = new Guid("89fa23ba-749b-460b-9882-f3cbbd76a1cd"),
                            BookId = new Guid("cfb4956c-43fb-4b1b-a430-28a65746b1cd")
                        },
                        new
                        {
                            GenreId = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            BookId = new Guid("cfb4956c-43fb-4b1b-a430-28a65746b1cd")
                        },
                        new
                        {
                            GenreId = new Guid("8cb9facc-e26e-4ce2-8765-f7a3a291f955"),
                            BookId = new Guid("cfb4956c-43fb-4b1b-a430-28a65746b1cd")
                        },
                        new
                        {
                            GenreId = new Guid("8cb9facc-e26e-4ce2-8765-f7a3a291f955"),
                            BookId = new Guid("24a8866e-827a-4324-9b9c-62cdf0219945")
                        },
                        new
                        {
                            GenreId = new Guid("09c11eca-5c58-465d-92fc-6891e2c6cf49"),
                            BookId = new Guid("24a8866e-827a-4324-9b9c-62cdf0219945")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("4955bb49-bf12-463a-8cb4-e0d0b396d332")
                        },
                        new
                        {
                            GenreId = new Guid("f8e30203-770d-458f-856b-427734a58afc"),
                            BookId = new Guid("4955bb49-bf12-463a-8cb4-e0d0b396d332")
                        },
                        new
                        {
                            GenreId = new Guid("64bc61c1-7a4c-4844-bc02-17ab6b5ae64d"),
                            BookId = new Guid("3c2b33e0-d08c-4306-aa43-75459237deb3")
                        },
                        new
                        {
                            GenreId = new Guid("291470b7-2128-447f-ab64-8f82770c74a2"),
                            BookId = new Guid("e3959340-6a6e-45f5-a75d-3741be5f9951")
                        },
                        new
                        {
                            GenreId = new Guid("0e3ce01e-df95-451f-a59d-8774501c6bef"),
                            BookId = new Guid("e3959340-6a6e-45f5-a75d-3741be5f9951")
                        },
                        new
                        {
                            GenreId = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            BookId = new Guid("e3959340-6a6e-45f5-a75d-3741be5f9951")
                        },
                        new
                        {
                            GenreId = new Guid("89fa23ba-749b-460b-9882-f3cbbd76a1cd"),
                            BookId = new Guid("e4543b2c-6472-46b6-836c-68839f50a9d9")
                        },
                        new
                        {
                            GenreId = new Guid("3a42bd69-50f4-49cc-9184-55d97bc930d4"),
                            BookId = new Guid("8725a3db-2f1a-409e-ad30-6cba94531ae2")
                        },
                        new
                        {
                            GenreId = new Guid("291470b7-2128-447f-ab64-8f82770c74a2"),
                            BookId = new Guid("0e9ed85f-a740-4650-b1c8-fc18d7969768")
                        },
                        new
                        {
                            GenreId = new Guid("8cb9facc-e26e-4ce2-8765-f7a3a291f955"),
                            BookId = new Guid("d898a657-04bd-4d2e-a9c9-330ce533e413")
                        },
                        new
                        {
                            GenreId = new Guid("d6fbd6be-632f-4f0d-b2f2-1776e1f068e1"),
                            BookId = new Guid("d898a657-04bd-4d2e-a9c9-330ce533e413")
                        },
                        new
                        {
                            GenreId = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            BookId = new Guid("d898a657-04bd-4d2e-a9c9-330ce533e413")
                        },
                        new
                        {
                            GenreId = new Guid("35140fdb-06f1-4edb-be27-b02a1a44d91f"),
                            BookId = new Guid("d898a657-04bd-4d2e-a9c9-330ce533e413")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("97d2692c-db28-478f-a5f9-1e55798b9bbf")
                        },
                        new
                        {
                            GenreId = new Guid("2c26cd80-e2e9-480a-8ce2-089e4545e01b"),
                            BookId = new Guid("33bbb4b8-b362-4e69-aaba-a2d588ae02b3")
                        },
                        new
                        {
                            GenreId = new Guid("3a42bd69-50f4-49cc-9184-55d97bc930d4"),
                            BookId = new Guid("33bbb4b8-b362-4e69-aaba-a2d588ae02b3")
                        },
                        new
                        {
                            GenreId = new Guid("d47c0cf6-5484-4b59-8426-9d8f2e34812d"),
                            BookId = new Guid("33bbb4b8-b362-4e69-aaba-a2d588ae02b3")
                        },
                        new
                        {
                            GenreId = new Guid("f8e30203-770d-458f-856b-427734a58afc"),
                            BookId = new Guid("369d6a60-c748-4526-aa5b-961b3d7a80fe")
                        },
                        new
                        {
                            GenreId = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            BookId = new Guid("369d6a60-c748-4526-aa5b-961b3d7a80fe")
                        },
                        new
                        {
                            GenreId = new Guid("234e659d-7919-4a3a-8e6c-8a6b58c7dae4"),
                            BookId = new Guid("12f83231-03b4-4ebb-bb24-340c84263253")
                        },
                        new
                        {
                            GenreId = new Guid("3a42bd69-50f4-49cc-9184-55d97bc930d4"),
                            BookId = new Guid("12f83231-03b4-4ebb-bb24-340c84263253")
                        },
                        new
                        {
                            GenreId = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            BookId = new Guid("9e2d481b-874f-4587-a842-072098955bcb")
                        },
                        new
                        {
                            GenreId = new Guid("64bc61c1-7a4c-4844-bc02-17ab6b5ae64d"),
                            BookId = new Guid("9e2d481b-874f-4587-a842-072098955bcb")
                        },
                        new
                        {
                            GenreId = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            BookId = new Guid("9e2d481b-874f-4587-a842-072098955bcb")
                        },
                        new
                        {
                            GenreId = new Guid("8cb9facc-e26e-4ce2-8765-f7a3a291f955"),
                            BookId = new Guid("9a147065-60a7-453b-b3ae-80bc4b4156d9")
                        },
                        new
                        {
                            GenreId = new Guid("d47c0cf6-5484-4b59-8426-9d8f2e34812d"),
                            BookId = new Guid("bbf49d78-4fc9-4b0d-8e8e-7ca5e72a03c8")
                        },
                        new
                        {
                            GenreId = new Guid("d47c0cf6-5484-4b59-8426-9d8f2e34812d"),
                            BookId = new Guid("0ec261fb-35e3-402b-b4d0-c30ecb4a34eb")
                        },
                        new
                        {
                            GenreId = new Guid("09c11eca-5c58-465d-92fc-6891e2c6cf49"),
                            BookId = new Guid("0ec261fb-35e3-402b-b4d0-c30ecb4a34eb")
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BookHireItem", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookHireCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("BookHireExpiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("BookReturnDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsBookReturned")
                        .HasColumnType("bit");

                    b.HasKey("BookId", "BookHireCardId");

                    b.HasIndex("BookHireCardId");

                    b.ToTable("BookHireItems");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BooksHireRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("BooksHiredDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("BooksHireRecords");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8bbdf7f-685e-4915-b2e9-19b95b8b5ccb"),
                            Title = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("89fa23ba-749b-460b-9882-f3cbbd76a1cd"),
                            Title = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("64bc61c1-7a4c-4844-bc02-17ab6b5ae64d"),
                            Title = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("291470b7-2128-447f-ab64-8f82770c74a2"),
                            Title = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("d6fbd6be-632f-4f0d-b2f2-1776e1f068e1"),
                            Title = "Romance"
                        },
                        new
                        {
                            Id = new Guid("2c26cd80-e2e9-480a-8ce2-089e4545e01b"),
                            Title = "Historical Fiction"
                        },
                        new
                        {
                            Id = new Guid("35140fdb-06f1-4edb-be27-b02a1a44d91f"),
                            Title = "Horror"
                        },
                        new
                        {
                            Id = new Guid("0e3ce01e-df95-451f-a59d-8774501c6bef"),
                            Title = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("234e659d-7919-4a3a-8e6c-8a6b58c7dae4"),
                            Title = "Non-Fiction"
                        },
                        new
                        {
                            Id = new Guid("09c11eca-5c58-465d-92fc-6891e2c6cf49"),
                            Title = "Biography"
                        },
                        new
                        {
                            Id = new Guid("f8e30203-770d-458f-856b-427734a58afc"),
                            Title = "Drama"
                        },
                        new
                        {
                            Id = new Guid("d47c0cf6-5484-4b59-8426-9d8f2e34812d"),
                            Title = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("08f3d6aa-1874-41c2-925c-58457cfabaac"),
                            Title = "Poetry"
                        },
                        new
                        {
                            Id = new Guid("3a42bd69-50f4-49cc-9184-55d97bc930d4"),
                            Title = "Self-Help"
                        },
                        new
                        {
                            Id = new Guid("8cb9facc-e26e-4ce2-8765-f7a3a291f955"),
                            Title = "Cookbook"
                        },
                        new
                        {
                            Id = new Guid("b39859ba-ff41-4f82-be87-bacdeb8e2c0a"),
                            Title = "Science"
                        },
                        new
                        {
                            Id = new Guid("76b8ab13-b3cd-49a6-84b5-3706e811bdb0"),
                            Title = "Business"
                        },
                        new
                        {
                            Id = new Guid("c4bd476f-ac4f-44e6-9ad4-0eabd7b1ff36"),
                            Title = "Travel"
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Book", b =>
                {
                    b.HasOne("TestTask.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BookGenre", b =>
                {
                    b.HasOne("TestTask.Domain.Entities.Book", "Book")
                        .WithMany("Genres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTask.Domain.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BookHireItem", b =>
                {
                    b.HasOne("TestTask.Domain.Entities.BooksHireRecord", "BookHireCard")
                        .WithMany("Books")
                        .HasForeignKey("BookHireCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTask.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookHireCard");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Book", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BooksHireRecord", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
