// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.DAL;

#nullable disable

namespace TestTask.DAL.Migrations
{
    [DbContext(typeof(TestTaskDbContext))]
    [Migration("20231207135450_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d35ffd89-61e4-4887-a791-900edfd36d69"),
                            FullName = "Jane Austen"
                        },
                        new
                        {
                            Id = new Guid("10615a81-8d9b-4099-9822-4081efd7a4ad"),
                            FullName = "Charles Dickens"
                        },
                        new
                        {
                            Id = new Guid("93c9b236-d56d-40bc-84ca-317bb83293aa"),
                            FullName = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = new Guid("19505c06-e688-41db-8d00-1561dd1ea93c"),
                            FullName = "J.K. Rowling"
                        },
                        new
                        {
                            Id = new Guid("f62dee0b-c18a-442e-be3f-64de2e4aeb32"),
                            FullName = "Agatha Christie"
                        },
                        new
                        {
                            Id = new Guid("1335fa2c-6bee-4c35-8735-d17c36ae1a36"),
                            FullName = "George Orwell"
                        },
                        new
                        {
                            Id = new Guid("47e1c0cc-aca2-42a5-8ef2-f3aa7007b9ea"),
                            FullName = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = new Guid("7c2bd8f5-b60a-43af-a892-6ee2370f9d1e"),
                            FullName = "William Shakespeare"
                        },
                        new
                        {
                            Id = new Guid("3207664e-10e9-4f4c-bebc-000cb20a8ac2"),
                            FullName = "Mark Twain"
                        },
                        new
                        {
                            Id = new Guid("e46d2a3b-9e03-4985-9208-49aab09348b4"),
                            FullName = "Gabriel García Márquez"
                        },
                        new
                        {
                            Id = new Guid("b49ab307-235b-4659-b4bd-e93280ac84e4"),
                            FullName = "Harper Lee"
                        },
                        new
                        {
                            Id = new Guid("87c47796-9894-455c-89c4-d548e9796f52"),
                            FullName = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = new Guid("a5aac66c-1ed9-4886-8ef4-c6be46575b4b"),
                            FullName = "Homer"
                        },
                        new
                        {
                            Id = new Guid("504246ec-9bcf-4c26-a705-8cf4abff4f4b"),
                            FullName = "Stephen King"
                        },
                        new
                        {
                            Id = new Guid("b5f1b0b3-0943-4d0a-a3c4-22d25836da0f"),
                            FullName = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = new Guid("42a87a56-af52-47e5-8c07-86d76adfcf82"),
                            FullName = "Emily Brontë"
                        },
                        new
                        {
                            Id = new Guid("45123b57-2088-4bdf-b180-cfe1ce4c0963"),
                            FullName = "Virginia Woolf"
                        },
                        new
                        {
                            Id = new Guid("01ed4143-30d8-4f84-9b61-cf32cc8cd3f7"),
                            FullName = "Charlotte Brontë"
                        },
                        new
                        {
                            Id = new Guid("b19d3bed-bb80-4747-a915-cb3fce01e8a5"),
                            FullName = "Arthur Conan Doyle"
                        },
                        new
                        {
                            Id = new Guid("6de5652f-7d06-44e8-bffd-541d99f45dbc"),
                            FullName = "Ayn Rand"
                        },
                        new
                        {
                            Id = new Guid("de6de5e2-0f17-4c0c-a8a3-bc2b267f211a"),
                            FullName = "Jane Goodall"
                        },
                        new
                        {
                            Id = new Guid("143b8492-16d6-486b-9f89-c5b08dd62117"),
                            FullName = "Michael Crichton"
                        },
                        new
                        {
                            Id = new Guid("eb484b53-5635-46c4-baaa-ed805b0dbead"),
                            FullName = "Isaac Asimov"
                        },
                        new
                        {
                            Id = new Guid("3e7dcc67-ca24-4711-a948-4f9e714e6925"),
                            FullName = "Margaret Atwood"
                        },
                        new
                        {
                            Id = new Guid("f4f0c1ad-c4d7-4ad3-9831-d17654c98836"),
                            FullName = "Kurt Vonnegut"
                        },
                        new
                        {
                            Id = new Guid("20042ed7-a09a-4b91-adac-cb298b87b007"),
                            FullName = "H.G. Wells"
                        },
                        new
                        {
                            Id = new Guid("58a4d4b6-d03b-4b2c-ac7b-e639bdce2068"),
                            FullName = "Roald Dahl"
                        },
                        new
                        {
                            Id = new Guid("9392e91e-5115-4a66-86cb-a0a70d6df27c"),
                            FullName = "Hermann Hesse"
                        },
                        new
                        {
                            Id = new Guid("69fd8ca4-a2b0-4cf6-a71a-308a50226a6f"),
                            FullName = "Aldous Huxley"
                        },
                        new
                        {
                            Id = new Guid("bb1fa7e6-828f-4557-a86e-475a133072c7"),
                            FullName = "Toni Morrison"
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f160540c-8401-4be1-ba0d-a9f75734d158"),
                            AuthorId = new Guid("d35ffd89-61e4-4887-a791-900edfd36d69"),
                            Description = "A timeless tale of love, manners, and societal expectations in Regency-era England by Jane Austen.",
                            ISBN = "978-0-14-143951-8",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("b8b260e2-448e-4d31-9cdf-1f36013f70de"),
                            AuthorId = new Guid("d35ffd89-61e4-4887-a791-900edfd36d69"),
                            Description = "Harper Lee's powerful exploration of racial injustice and moral growth in the American South.",
                            ISBN = "978-0-06-112348-4",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("a823a0cc-6a32-474a-b4b2-37c94549327f"),
                            AuthorId = new Guid("42a87a56-af52-47e5-8c07-86d76adfcf82"),
                            Description = "George Orwell's dystopian masterpiece, depicting a nightmarish future under totalitarian rule.",
                            ISBN = "978-0-45-152493-5",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("abe7d045-c701-4d61-81b1-b7d1d2f28c39"),
                            AuthorId = new Guid("42a87a56-af52-47e5-8c07-86d76adfcf82"),
                            Description = "F. Scott Fitzgerald's classic portrayal of the American Dream, excess, and disillusionment in the Roaring Twenties.",
                            ISBN = "978-0-74-327356-5",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("cd57b50b-3734-43d7-9229-4f656d8d6aa6"),
                            AuthorId = new Guid("1335fa2c-6bee-4c35-8735-d17c36ae1a36"),
                            Description = "J.K. Rowling's enchanting introduction to the wizarding world, filled with magic, friendship, and adventure.",
                            ISBN = "978-0-59-035342-7",
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = new Guid("219b255f-8434-426c-a236-b16b224f557a"),
                            AuthorId = new Guid("3e7dcc67-ca24-4711-a948-4f9e714e6925"),
                            ISBN = "978-0-54-792822-7",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("566c9af3-6bbb-45a4-81f0-5d8572a8e577"),
                            AuthorId = new Guid("42a87a56-af52-47e5-8c07-86d76adfcf82"),
                            Description = "J.D. Salinger's iconic coming-of-age novel, capturing the angst and rebellion of a teenage boy in post-World War II America.",
                            ISBN = "978-0-31-676948-0",
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = new Guid("7baa369b-b5d5-419b-b1df-78f31306e129"),
                            AuthorId = new Guid("10615a81-8d9b-4099-9822-4081efd7a4ad"),
                            Description = "Leo Tolstoy's epic portrayal of Russian society during the Napoleonic Wars, blending history, philosophy, and human drama.",
                            ISBN = "978-0-14-303500-8",
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = new Guid("bc79faf2-e3e5-4056-8f61-4b9d6b69aadd"),
                            AuthorId = new Guid("9392e91e-5115-4a66-86cb-a0a70d6df27c"),
                            Description = "Homer's ancient Greek epic, recounting the adventures of Odysseus as he journeys home from the Trojan War.",
                            ISBN = "978-0-14-303995-2",
                            Title = "The Odyssey"
                        },
                        new
                        {
                            Id = new Guid("c2e43fe6-58ab-4aa7-bacd-49b175d565ad"),
                            AuthorId = new Guid("6de5652f-7d06-44e8-bffd-541d99f45dbc"),
                            ISBN = "978-0-06-085052-4",
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = new Guid("84914b05-f2c9-4346-a656-8bd4a5bc3e40"),
                            AuthorId = new Guid("504246ec-9bcf-4c26-a705-8cf4abff4f4b"),
                            Description = "J.R.R. Tolkien's epic fantasy trilogy, featuring the quest to destroy the One Ring and save Middle-earth from the dark forces of Sauron.",
                            ISBN = "978-0-54-400341-5",
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("cb38da87-20f3-4540-83d0-032e6a87d35d"),
                            AuthorId = new Guid("69fd8ca4-a2b0-4cf6-a71a-308a50226a6f"),
                            Description = "Mary Shelley's gothic tale of scientific hubris and the consequences of creating life.",
                            ISBN = "978-0-48-628211-4",
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = new Guid("479298bc-c19e-4bd4-9246-3e7800f2e5d5"),
                            AuthorId = new Guid("6de5652f-7d06-44e8-bffd-541d99f45dbc"),
                            Description = "Fyodor Dostoevsky's psychological thriller, exploring the moral and psychological turmoil of a young man in St. Petersburg.",
                            ISBN = "978-0-14-310763-7",
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = new Guid("a4ed7151-9852-4c9c-92db-a705664345ea"),
                            AuthorId = new Guid("1335fa2c-6bee-4c35-8735-d17c36ae1a36"),
                            ISBN = "978-0-06-112028-4",
                            Title = "One Hundred Years of Solitude"
                        },
                        new
                        {
                            Id = new Guid("5f6c0fa6-e5ad-4066-8f69-82f74491259d"),
                            AuthorId = new Guid("47e1c0cc-aca2-42a5-8ef2-f3aa7007b9ea"),
                            Description = "C.S. Lewis's beloved fantasy series, taking readers to the enchanting land of Narnia and its magical inhabitants.",
                            ISBN = "978-0-06-112008-4",
                            Title = "The Chronicles of Narnia"
                        },
                        new
                        {
                            Id = new Guid("c466c891-c61d-4cb8-baca-a61ae803b5f2"),
                            AuthorId = new Guid("6de5652f-7d06-44e8-bffd-541d99f45dbc"),
                            Description = "Douglas Adams's hilarious space adventure, following the misadventures of Arthur Dent and his extraterrestrial friend Ford Prefect.",
                            ISBN = "978-0-34-539180-3",
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = new Guid("e170cc7a-e522-41ce-bc8a-21a3fabce3f6"),
                            AuthorId = new Guid("de6de5e2-0f17-4c0c-a8a3-bc2b267f211a"),
                            Description = "Stephen King's chilling tale of supernatural horror, isolation, and the descent into madness at the haunted Overlook Hotel.",
                            ISBN = "978-0-38-511683-7",
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = new Guid("5e3eda09-3e3a-442f-afaf-c068082934df"),
                            AuthorId = new Guid("eb484b53-5635-46c4-baaa-ed805b0dbead"),
                            Description = "Herman Melville's epic journey aboard the whaling ship Pequod, driven by Captain Ahab's obsessive quest for the white whale.",
                            ISBN = "978-0-14-310635-7",
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            Id = new Guid("6c51c4c2-ad34-4cd0-8d50-beac7e524025"),
                            AuthorId = new Guid("de6de5e2-0f17-4c0c-a8a3-bc2b267f211a"),
                            ISBN = "978-0-19-921613-3",
                            Title = "Alice's Adventures in Wonderland"
                        },
                        new
                        {
                            Id = new Guid("f5a7f53c-0fa7-4d10-94c4-beba2e0cbbdd"),
                            AuthorId = new Guid("d35ffd89-61e4-4887-a791-900edfd36d69"),
                            Description = "Stieg Larsson's gripping mystery featuring investigative journalist Mikael Blomkvist and the enigmatic hacker Lisbeth Salander.",
                            ISBN = "978-0-30-726975-1",
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            Id = new Guid("669fb617-f96d-47cf-b3bd-359569fb4aa7"),
                            AuthorId = new Guid("504246ec-9bcf-4c26-a705-8cf4abff4f4b"),
                            Description = "Suzanne Collins's dystopian saga of Katniss Everdeen's fight for survival in the annual Hunger Games.",
                            ISBN = "978-0-43-902352-8",
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            Id = new Guid("89bb92e6-7847-4bfe-8d30-026a3a0519bb"),
                            AuthorId = new Guid("b19d3bed-bb80-4747-a915-cb3fce01e8a5"),
                            Description = "Frank Herbert's science fiction epic set in a distant future where noble houses vie for control of the desert planet Arrakis and its valuable spice melange.",
                            ISBN = "978-0-44-117271-9",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = new Guid("d2030d67-e15c-4ccc-b5ea-e769be2dbe17"),
                            AuthorId = new Guid("143b8492-16d6-486b-9f89-c5b08dd62117"),
                            Description = "Fyodor Dostoevsky's exploration of morality, faith, and family dynamics through the complex relationships of the Karamazov brothers.",
                            ISBN = "978-0-14-044924-2",
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            Id = new Guid("1475e87b-c7e8-4372-8de5-2bd6b17bb4d2"),
                            AuthorId = new Guid("143b8492-16d6-486b-9f89-c5b08dd62117"),
                            ISBN = "978-0-14-143955-6",
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            Id = new Guid("bc9c8649-c943-4ecb-87e8-11b6d8d9d112"),
                            AuthorId = new Guid("eb484b53-5635-46c4-baaa-ed805b0dbead"),
                            Description = "Geoffrey Chaucer's collection of stories told by a diverse group of pilgrims on their journey to Canterbury.",
                            ISBN = "978-0-14-042234-4",
                            Title = "The Canterbury Tales"
                        },
                        new
                        {
                            Id = new Guid("943df911-4772-4185-9857-1ca1aa395206"),
                            AuthorId = new Guid("19505c06-e688-41db-8d00-1561dd1ea93c"),
                            ISBN = "978-0-14-143957-0",
                            Title = "The Picture of Dorian Gray"
                        },
                        new
                        {
                            Id = new Guid("4be039c0-322c-49ea-909d-f5967ad47cf2"),
                            AuthorId = new Guid("19505c06-e688-41db-8d00-1561dd1ea93c"),
                            Description = "Paulo Coelho's philosophical novel about Santiago, a shepherd boy, on a journey to discover his personal legend.",
                            ISBN = "978-0-06-112241-5",
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = new Guid("fa121db7-0442-451e-a664-3945d213ba28"),
                            AuthorId = new Guid("f4f0c1ad-c4d7-4ad3-9831-d17654c98836"),
                            Description = "Margaret Atwood's dystopian novel set in the Republic of Gilead, where women's rights are severely restricted.",
                            ISBN = "978-0-38-549081-8",
                            Title = "The Handmaid's Tale"
                        },
                        new
                        {
                            Id = new Guid("f6d21620-e4db-4380-a28c-e1619eb88fd6"),
                            AuthorId = new Guid("58a4d4b6-d03b-4b2c-ac7b-e639bdce2068"),
                            Description = "Cormac McCarthy's post-apocalyptic tale of a father and son's harrowing journey through a desolate landscape.",
                            ISBN = "978-0-30-738789-9",
                            Title = "The Road"
                        },
                        new
                        {
                            Id = new Guid("687ab10d-302d-424a-88d7-cc3fb53bdc2b"),
                            AuthorId = new Guid("f4f0c1ad-c4d7-4ad3-9831-d17654c98836"),
                            Description = "Alexandre Dumas's classic adventure novel of betrayal, revenge, and redemption.",
                            ISBN = "978-0-14-044926-6",
                            Title = "The Count of Monte Cristo"
                        },
                        new
                        {
                            Id = new Guid("6b0cc103-b8e6-401c-a3ec-769eace927eb"),
                            AuthorId = new Guid("b19d3bed-bb80-4747-a915-cb3fce01e8a5"),
                            ISBN = "978-0-45-141943-9",
                            Title = "Les Misérables"
                        },
                        new
                        {
                            Id = new Guid("539f03dd-b40a-402b-bc78-02f909b97538"),
                            AuthorId = new Guid("42a87a56-af52-47e5-8c07-86d76adfcf82"),
                            Description = "Joseph Heller's satirical novel depicting the absurdities and paradoxes of war.",
                            ISBN = "978-0-68-484121-9",
                            Title = "The Catch-22"
                        },
                        new
                        {
                            Id = new Guid("aa47c42b-d820-42aa-bd2f-f1244e75e31c"),
                            AuthorId = new Guid("b5f1b0b3-0943-4d0a-a3c4-22d25836da0f"),
                            ISBN = "978-0-15-602835-6",
                            Title = "The Color Purple"
                        },
                        new
                        {
                            Id = new Guid("f417d3f1-9e2e-4035-b878-71a1f5a82c0c"),
                            AuthorId = new Guid("6de5652f-7d06-44e8-bffd-541d99f45dbc"),
                            Description = "Ken Kesey's classic novel set in a mental hospital, challenging authority and celebrating individuality.",
                            ISBN = "978-0-45-116396-7",
                            Title = "One Flew Over the Cuckoo's Nest"
                        },
                        new
                        {
                            Id = new Guid("91a21725-f427-48a8-929c-c3e91dbba110"),
                            AuthorId = new Guid("9392e91e-5115-4a66-86cb-a0a70d6df27c"),
                            Description = "Andy Weir's gripping science fiction novel about an astronaut stranded on Mars and his fight for survival.",
                            ISBN = "978-0-55-341802-6",
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = new Guid("d55f22a5-3078-4960-bdd7-3bccff1d14cc"),
                            AuthorId = new Guid("a5aac66c-1ed9-4886-8ef4-c6be46575b4b"),
                            Description = "Khaled Hosseini's powerful novel about friendship, betrayal, and redemption in Afghanistan.",
                            ISBN = "978-1-59-463193-1",
                            Title = "The Kite Runner"
                        },
                        new
                        {
                            Id = new Guid("725187d4-fa2a-4bee-9cb8-1ed031088cb7"),
                            AuthorId = new Guid("3e7dcc67-ca24-4711-a948-4f9e714e6925"),
                            ISBN = "978-1-25-030169-7",
                            Title = "The Silent Patient"
                        },
                        new
                        {
                            Id = new Guid("b72491e2-d80d-49eb-b79a-28a7c34fa92d"),
                            AuthorId = new Guid("de6de5e2-0f17-4c0c-a8a3-bc2b267f211a"),
                            Description = "Tara Westover's memoir recounting her journey from a rural Idaho childhood to gaining an education against all odds.",
                            ISBN = "978-0-52-558019-4",
                            Title = "Educated"
                        },
                        new
                        {
                            Id = new Guid("6cb782b0-5ca8-403a-b6b3-1c1f5440ec2e"),
                            AuthorId = new Guid("b19d3bed-bb80-4747-a915-cb3fce01e8a5"),
                            Description = "Yuval Noah Harari's exploration of the history and impact of Homo sapiens on the world.",
                            ISBN = "978-0-99-711060-8",
                            Title = "Sapiens: A Brief History of Humankind"
                        },
                        new
                        {
                            Id = new Guid("23030c7e-bb55-4ce2-aefa-bba3cf25bf97"),
                            AuthorId = new Guid("87c47796-9894-455c-89c4-d548e9796f52"),
                            Description = "Donna Tartt's Pulitzer Prize-winning novel about a young boy's life after a terrorist attack in a New York art museum.",
                            ISBN = "978-0-31-605543-7",
                            Title = "The Goldfinch"
                        },
                        new
                        {
                            Id = new Guid("86aa7b8b-07d0-4f57-b5e5-f01f676dbe69"),
                            AuthorId = new Guid("7c2bd8f5-b60a-43af-a892-6ee2370f9d1e"),
                            Description = "Erin Morgenstern's magical tale of a mysterious competition between two illusionists in a magical circus.",
                            ISBN = "978-0-38-553970-6",
                            Title = "The Night Circus"
                        },
                        new
                        {
                            Id = new Guid("628fc3a2-c351-4b6e-9a1d-d80d63711976"),
                            AuthorId = new Guid("eb484b53-5635-46c4-baaa-ed805b0dbead"),
                            Description = "Rebecca Skloot's biography exploring the life and legacy of Henrietta Lacks, whose cells were used for medical research without her knowledge.",
                            ISBN = "978-1-40-005217-2",
                            Title = "The Immortal Life of Henrietta Lacks"
                        },
                        new
                        {
                            Id = new Guid("eb8227df-e352-4659-851a-f36106186a9a"),
                            AuthorId = new Guid("10615a81-8d9b-4099-9822-4081efd7a4ad"),
                            Description = "John Green's heart-wrenching novel about two teenagers with cancer who fall in love.",
                            ISBN = "978-0-14-242417-9",
                            Title = "The Fault in Our Stars"
                        },
                        new
                        {
                            Id = new Guid("86b2636c-0f1c-44f8-ade9-e9437f5bd1da"),
                            AuthorId = new Guid("f62dee0b-c18a-442e-be3f-64de2e4aeb32"),
                            Description = "M. Scott Peck's exploration of personal growth, love, and spiritual development.",
                            ISBN = "978-0-74-324315-8",
                            Title = "The Road Less Traveled"
                        },
                        new
                        {
                            Id = new Guid("8cb48997-f476-4cfc-9ef2-ef89af50fd3c"),
                            AuthorId = new Guid("de6de5e2-0f17-4c0c-a8a3-bc2b267f211a"),
                            Description = "Paula Hawkins's psychological thriller about a woman who becomes entangled in a missing person investigation.",
                            ISBN = "978-1-59-463402-4",
                            Title = "The Girl on the Train"
                        },
                        new
                        {
                            Id = new Guid("ef708df4-7cc7-4b5f-8b78-6c5104f8e100"),
                            AuthorId = new Guid("143b8492-16d6-486b-9f89-c5b08dd62117"),
                            Description = "Dan Brown's gripping mystery involving symbology, art, and secret societies.",
                            ISBN = "978-0-30-747427-8",
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = new Guid("fbaad571-7547-4f12-8541-ff4c011d6482"),
                            AuthorId = new Guid("87c47796-9894-455c-89c4-d548e9796f52"),
                            Description = "Kathryn Stockett's novel about African American maids working in white households in Jackson, Mississippi, during the early 1960s.",
                            ISBN = "978-0-42-523220-0",
                            Title = "The Help"
                        },
                        new
                        {
                            Id = new Guid("41dd2dd8-7c58-4ab8-9ea1-b35c57366080"),
                            AuthorId = new Guid("b19d3bed-bb80-4747-a915-cb3fce01e8a5"),
                            ISBN = "978-0-14-044022-5",
                            Title = "The Three Musketeers"
                        },
                        new
                        {
                            Id = new Guid("9cece5b1-d2c5-4f34-a19f-54ee61b76b47"),
                            AuthorId = new Guid("de6de5e2-0f17-4c0c-a8a3-bc2b267f211a"),
                            Description = "Haruki Murakami's surreal and mesmerizing novel exploring the mysteries of human consciousness.",
                            ISBN = "978-0-67-977543-0",
                            Title = "The Wind-Up Bird Chronicle"
                        },
                        new
                        {
                            Id = new Guid("529ee040-5ed8-42ed-be65-e05c4be21528"),
                            AuthorId = new Guid("6de5652f-7d06-44e8-bffd-541d99f45dbc"),
                            ISBN = "978-0-37-584220-7",
                            Title = "The Book Thief"
                        },
                        new
                        {
                            Id = new Guid("39c21217-e288-4b21-90da-68dbec7b7e8f"),
                            AuthorId = new Guid("7c2bd8f5-b60a-43af-a892-6ee2370f9d1e"),
                            Description = "Amy Tan's novel exploring the relationships between Chinese-American immigrant mothers and their American-born daughters.",
                            ISBN = "978-0-80-417839-9",
                            Title = "The Joy Luck Club"
                        },
                        new
                        {
                            Id = new Guid("5bca57fb-4f16-4619-a0f4-261a2c7c691c"),
                            AuthorId = new Guid("47e1c0cc-aca2-42a5-8ef2-f3aa7007b9ea"),
                            Description = "John Steinbeck's novel depicting the struggles of a displaced Oklahoma family during the Great Depression.",
                            ISBN = "978-0-14-303943-3",
                            Title = "The Grapes of Wrath"
                        },
                        new
                        {
                            Id = new Guid("fdaff6b9-0881-449f-b921-d9853cd2d725"),
                            AuthorId = new Guid("19505c06-e688-41db-8d00-1561dd1ea93c"),
                            Description = "Charles Duhigg's exploration of the science behind habits and how they can be transformed.",
                            ISBN = "978-0-81-298160-5",
                            Title = "The Power of Habit"
                        },
                        new
                        {
                            Id = new Guid("ea98eb91-35a7-4638-8d81-9df9bcf55e47"),
                            AuthorId = new Guid("d35ffd89-61e4-4887-a791-900edfd36d69"),
                            ISBN = "978-0-14-200174-5",
                            Title = "The Secret Life of Bees"
                        },
                        new
                        {
                            Id = new Guid("268c1d81-e4b4-4f5f-8993-2d80473050a3"),
                            AuthorId = new Guid("3e7dcc67-ca24-4711-a948-4f9e714e6925"),
                            ISBN = "978-0-52-551488-0",
                            Title = "The Immortalists"
                        },
                        new
                        {
                            Id = new Guid("c76dd43e-0e97-4692-84cb-8d4f2b8451df"),
                            AuthorId = new Guid("e46d2a3b-9e03-4985-9208-49aab09348b4"),
                            Description = "Jeannette Walls's memoir detailing her unconventional and often troubled childhood.",
                            ISBN = "978-0-74-324754-5",
                            Title = "The Glass Castle"
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BookGenre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenreId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BooksGenres");

                    b.HasData(
                        new
                        {
                            GenreId = new Guid("3552e9af-420f-4ac5-b2a7-1c2df67ea04d"),
                            BookId = new Guid("f160540c-8401-4be1-ba0d-a9f75734d158")
                        },
                        new
                        {
                            GenreId = new Guid("600d8d8a-a57a-4fa9-83ec-40fa7ebe45ba"),
                            BookId = new Guid("b8b260e2-448e-4d31-9cdf-1f36013f70de")
                        },
                        new
                        {
                            GenreId = new Guid("4d56568a-f1f7-46a0-b2aa-a5cf89f033f3"),
                            BookId = new Guid("a823a0cc-6a32-474a-b4b2-37c94549327f")
                        },
                        new
                        {
                            GenreId = new Guid("1f7e00a3-33bc-40e3-86cb-0cc3d5960bd9"),
                            BookId = new Guid("abe7d045-c701-4d61-81b1-b7d1d2f28c39")
                        },
                        new
                        {
                            GenreId = new Guid("3af32f58-6e4f-4cda-8ab5-e2a3c2930109"),
                            BookId = new Guid("cd57b50b-3734-43d7-9229-4f656d8d6aa6")
                        },
                        new
                        {
                            GenreId = new Guid("0cf8b380-2197-475e-b2a3-58933b2b28da"),
                            BookId = new Guid("cd57b50b-3734-43d7-9229-4f656d8d6aa6")
                        },
                        new
                        {
                            GenreId = new Guid("b621b43e-4639-44c1-9a30-9aaa12b2ac80"),
                            BookId = new Guid("566c9af3-6bbb-45a4-81f0-5d8572a8e577")
                        },
                        new
                        {
                            GenreId = new Guid("0cf8b380-2197-475e-b2a3-58933b2b28da"),
                            BookId = new Guid("7baa369b-b5d5-419b-b1df-78f31306e129")
                        },
                        new
                        {
                            GenreId = new Guid("3e9f2549-c5f1-49bc-a5c7-642104b6321e"),
                            BookId = new Guid("7baa369b-b5d5-419b-b1df-78f31306e129")
                        },
                        new
                        {
                            GenreId = new Guid("0cf8b380-2197-475e-b2a3-58933b2b28da"),
                            BookId = new Guid("bc79faf2-e3e5-4056-8f61-4b9d6b69aadd")
                        },
                        new
                        {
                            GenreId = new Guid("ce160fd7-cb8c-4185-99e2-f398e52678cc"),
                            BookId = new Guid("c2e43fe6-58ab-4aa7-bacd-49b175d565ad")
                        },
                        new
                        {
                            GenreId = new Guid("bc6621c3-2a57-4271-8820-93d94501eeba"),
                            BookId = new Guid("c2e43fe6-58ab-4aa7-bacd-49b175d565ad")
                        },
                        new
                        {
                            GenreId = new Guid("4d56568a-f1f7-46a0-b2aa-a5cf89f033f3"),
                            BookId = new Guid("c2e43fe6-58ab-4aa7-bacd-49b175d565ad")
                        },
                        new
                        {
                            GenreId = new Guid("6fdde76f-4321-4d4a-a7ed-83ed682a6d62"),
                            BookId = new Guid("84914b05-f2c9-4346-a656-8bd4a5bc3e40")
                        },
                        new
                        {
                            GenreId = new Guid("cfc35fd7-ff41-44bb-9779-dc0f98ad8eb2"),
                            BookId = new Guid("cb38da87-20f3-4540-83d0-032e6a87d35d")
                        },
                        new
                        {
                            GenreId = new Guid("5f9b5fb9-506d-4c07-80ef-e5b7fcc3b6f2"),
                            BookId = new Guid("cb38da87-20f3-4540-83d0-032e6a87d35d")
                        },
                        new
                        {
                            GenreId = new Guid("ce160fd7-cb8c-4185-99e2-f398e52678cc"),
                            BookId = new Guid("479298bc-c19e-4bd4-9246-3e7800f2e5d5")
                        },
                        new
                        {
                            GenreId = new Guid("cfc35fd7-ff41-44bb-9779-dc0f98ad8eb2"),
                            BookId = new Guid("479298bc-c19e-4bd4-9246-3e7800f2e5d5")
                        },
                        new
                        {
                            GenreId = new Guid("1f7e00a3-33bc-40e3-86cb-0cc3d5960bd9"),
                            BookId = new Guid("479298bc-c19e-4bd4-9246-3e7800f2e5d5")
                        },
                        new
                        {
                            GenreId = new Guid("3552e9af-420f-4ac5-b2a7-1c2df67ea04d"),
                            BookId = new Guid("a4ed7151-9852-4c9c-92db-a705664345ea")
                        },
                        new
                        {
                            GenreId = new Guid("a4adf827-2747-40d7-801b-07115f9f0082"),
                            BookId = new Guid("a4ed7151-9852-4c9c-92db-a705664345ea")
                        },
                        new
                        {
                            GenreId = new Guid("e0be5314-1296-4988-b09f-11fca7c85060"),
                            BookId = new Guid("a4ed7151-9852-4c9c-92db-a705664345ea")
                        },
                        new
                        {
                            GenreId = new Guid("3af32f58-6e4f-4cda-8ab5-e2a3c2930109"),
                            BookId = new Guid("5f6c0fa6-e5ad-4066-8f69-82f74491259d")
                        },
                        new
                        {
                            GenreId = new Guid("1f7e00a3-33bc-40e3-86cb-0cc3d5960bd9"),
                            BookId = new Guid("5f6c0fa6-e5ad-4066-8f69-82f74491259d")
                        },
                        new
                        {
                            GenreId = new Guid("cfc35fd7-ff41-44bb-9779-dc0f98ad8eb2"),
                            BookId = new Guid("c466c891-c61d-4cb8-baca-a61ae803b5f2")
                        },
                        new
                        {
                            GenreId = new Guid("3552e9af-420f-4ac5-b2a7-1c2df67ea04d"),
                            BookId = new Guid("c466c891-c61d-4cb8-baca-a61ae803b5f2")
                        },
                        new
                        {
                            GenreId = new Guid("0cf8b380-2197-475e-b2a3-58933b2b28da"),
                            BookId = new Guid("c466c891-c61d-4cb8-baca-a61ae803b5f2")
                        },
                        new
                        {
                            GenreId = new Guid("ce160fd7-cb8c-4185-99e2-f398e52678cc"),
                            BookId = new Guid("c466c891-c61d-4cb8-baca-a61ae803b5f2")
                        },
                        new
                        {
                            GenreId = new Guid("e0be5314-1296-4988-b09f-11fca7c85060"),
                            BookId = new Guid("e170cc7a-e522-41ce-bc8a-21a3fabce3f6")
                        },
                        new
                        {
                            GenreId = new Guid("5f9b5fb9-506d-4c07-80ef-e5b7fcc3b6f2"),
                            BookId = new Guid("e170cc7a-e522-41ce-bc8a-21a3fabce3f6")
                        },
                        new
                        {
                            GenreId = new Guid("1f7e00a3-33bc-40e3-86cb-0cc3d5960bd9"),
                            BookId = new Guid("e170cc7a-e522-41ce-bc8a-21a3fabce3f6")
                        },
                        new
                        {
                            GenreId = new Guid("3af32f58-6e4f-4cda-8ab5-e2a3c2930109"),
                            BookId = new Guid("e170cc7a-e522-41ce-bc8a-21a3fabce3f6")
                        },
                        new
                        {
                            GenreId = new Guid("5f9b5fb9-506d-4c07-80ef-e5b7fcc3b6f2"),
                            BookId = new Guid("5e3eda09-3e3a-442f-afaf-c068082934df")
                        },
                        new
                        {
                            GenreId = new Guid("1f7e00a3-33bc-40e3-86cb-0cc3d5960bd9"),
                            BookId = new Guid("5e3eda09-3e3a-442f-afaf-c068082934df")
                        },
                        new
                        {
                            GenreId = new Guid("5f9b5fb9-506d-4c07-80ef-e5b7fcc3b6f2"),
                            BookId = new Guid("f5a7f53c-0fa7-4d10-94c4-beba2e0cbbdd")
                        },
                        new
                        {
                            GenreId = new Guid("3552e9af-420f-4ac5-b2a7-1c2df67ea04d"),
                            BookId = new Guid("f5a7f53c-0fa7-4d10-94c4-beba2e0cbbdd")
                        },
                        new
                        {
                            GenreId = new Guid("ce160fd7-cb8c-4185-99e2-f398e52678cc"),
                            BookId = new Guid("f5a7f53c-0fa7-4d10-94c4-beba2e0cbbdd")
                        },
                        new
                        {
                            GenreId = new Guid("e0be5314-1296-4988-b09f-11fca7c85060"),
                            BookId = new Guid("f5a7f53c-0fa7-4d10-94c4-beba2e0cbbdd")
                        },
                        new
                        {
                            GenreId = new Guid("1f7e00a3-33bc-40e3-86cb-0cc3d5960bd9"),
                            BookId = new Guid("669fb617-f96d-47cf-b3bd-359569fb4aa7")
                        },
                        new
                        {
                            GenreId = new Guid("b621b43e-4639-44c1-9a30-9aaa12b2ac80"),
                            BookId = new Guid("89bb92e6-7847-4bfe-8d30-026a3a0519bb")
                        },
                        new
                        {
                            GenreId = new Guid("ce160fd7-cb8c-4185-99e2-f398e52678cc"),
                            BookId = new Guid("d2030d67-e15c-4ccc-b5ea-e769be2dbe17")
                        },
                        new
                        {
                            GenreId = new Guid("4d56568a-f1f7-46a0-b2aa-a5cf89f033f3"),
                            BookId = new Guid("d2030d67-e15c-4ccc-b5ea-e769be2dbe17")
                        },
                        new
                        {
                            GenreId = new Guid("16f86a14-951e-4d5d-a8a2-1b851bfedbf0"),
                            BookId = new Guid("1475e87b-c7e8-4372-8de5-2bd6b17bb4d2")
                        },
                        new
                        {
                            GenreId = new Guid("a4adf827-2747-40d7-801b-07115f9f0082"),
                            BookId = new Guid("943df911-4772-4185-9857-1ca1aa395206")
                        },
                        new
                        {
                            GenreId = new Guid("b621b43e-4639-44c1-9a30-9aaa12b2ac80"),
                            BookId = new Guid("4be039c0-322c-49ea-909d-f5967ad47cf2")
                        },
                        new
                        {
                            GenreId = new Guid("3af32f58-6e4f-4cda-8ab5-e2a3c2930109"),
                            BookId = new Guid("fa121db7-0442-451e-a664-3945d213ba28")
                        },
                        new
                        {
                            GenreId = new Guid("e0be5314-1296-4988-b09f-11fca7c85060"),
                            BookId = new Guid("fa121db7-0442-451e-a664-3945d213ba28")
                        },
                        new
                        {
                            GenreId = new Guid("4d56568a-f1f7-46a0-b2aa-a5cf89f033f3"),
                            BookId = new Guid("fa121db7-0442-451e-a664-3945d213ba28")
                        },
                        new
                        {
                            GenreId = new Guid("0cf8b380-2197-475e-b2a3-58933b2b28da"),
                            BookId = new Guid("687ab10d-302d-424a-88d7-cc3fb53bdc2b")
                        },
                        new
                        {
                            GenreId = new Guid("3af32f58-6e4f-4cda-8ab5-e2a3c2930109"),
                            BookId = new Guid("687ab10d-302d-424a-88d7-cc3fb53bdc2b")
                        },
                        new
                        {
                            GenreId = new Guid("a4adf827-2747-40d7-801b-07115f9f0082"),
                            BookId = new Guid("539f03dd-b40a-402b-bc78-02f909b97538")
                        },
                        new
                        {
                            GenreId = new Guid("4d56568a-f1f7-46a0-b2aa-a5cf89f033f3"),
                            BookId = new Guid("539f03dd-b40a-402b-bc78-02f909b97538")
                        },
                        new
                        {
                            GenreId = new Guid("5f9b5fb9-506d-4c07-80ef-e5b7fcc3b6f2"),
                            BookId = new Guid("539f03dd-b40a-402b-bc78-02f909b97538")
                        },
                        new
                        {
                            GenreId = new Guid("3552e9af-420f-4ac5-b2a7-1c2df67ea04d"),
                            BookId = new Guid("aa47c42b-d820-42aa-bd2f-f1244e75e31c")
                        },
                        new
                        {
                            GenreId = new Guid("6fdde76f-4321-4d4a-a7ed-83ed682a6d62"),
                            BookId = new Guid("aa47c42b-d820-42aa-bd2f-f1244e75e31c")
                        },
                        new
                        {
                            GenreId = new Guid("2407f9f6-9366-44cc-a778-a6542fbf117d"),
                            BookId = new Guid("f417d3f1-9e2e-4035-b878-71a1f5a82c0c")
                        },
                        new
                        {
                            GenreId = new Guid("0cf8b380-2197-475e-b2a3-58933b2b28da"),
                            BookId = new Guid("f417d3f1-9e2e-4035-b878-71a1f5a82c0c")
                        },
                        new
                        {
                            GenreId = new Guid("3552e9af-420f-4ac5-b2a7-1c2df67ea04d"),
                            BookId = new Guid("91a21725-f427-48a8-929c-c3e91dbba110")
                        },
                        new
                        {
                            GenreId = new Guid("600d8d8a-a57a-4fa9-83ec-40fa7ebe45ba"),
                            BookId = new Guid("d55f22a5-3078-4960-bdd7-3bccff1d14cc")
                        },
                        new
                        {
                            GenreId = new Guid("3552e9af-420f-4ac5-b2a7-1c2df67ea04d"),
                            BookId = new Guid("d55f22a5-3078-4960-bdd7-3bccff1d14cc")
                        },
                        new
                        {
                            GenreId = new Guid("cfc35fd7-ff41-44bb-9779-dc0f98ad8eb2"),
                            BookId = new Guid("725187d4-fa2a-4bee-9cb8-1ed031088cb7")
                        },
                        new
                        {
                            GenreId = new Guid("ce160fd7-cb8c-4185-99e2-f398e52678cc"),
                            BookId = new Guid("725187d4-fa2a-4bee-9cb8-1ed031088cb7")
                        },
                        new
                        {
                            GenreId = new Guid("16f86a14-951e-4d5d-a8a2-1b851bfedbf0"),
                            BookId = new Guid("725187d4-fa2a-4bee-9cb8-1ed031088cb7")
                        },
                        new
                        {
                            GenreId = new Guid("6fdde76f-4321-4d4a-a7ed-83ed682a6d62"),
                            BookId = new Guid("6cb782b0-5ca8-403a-b6b3-1c1f5440ec2e")
                        },
                        new
                        {
                            GenreId = new Guid("ce160fd7-cb8c-4185-99e2-f398e52678cc"),
                            BookId = new Guid("6cb782b0-5ca8-403a-b6b3-1c1f5440ec2e")
                        },
                        new
                        {
                            GenreId = new Guid("3e9f2549-c5f1-49bc-a5c7-642104b6321e"),
                            BookId = new Guid("23030c7e-bb55-4ce2-aefa-bba3cf25bf97")
                        },
                        new
                        {
                            GenreId = new Guid("6fdde76f-4321-4d4a-a7ed-83ed682a6d62"),
                            BookId = new Guid("86aa7b8b-07d0-4f57-b5e5-f01f676dbe69")
                        },
                        new
                        {
                            GenreId = new Guid("cfc35fd7-ff41-44bb-9779-dc0f98ad8eb2"),
                            BookId = new Guid("628fc3a2-c351-4b6e-9a1d-d80d63711976")
                        },
                        new
                        {
                            GenreId = new Guid("5f9b5fb9-506d-4c07-80ef-e5b7fcc3b6f2"),
                            BookId = new Guid("eb8227df-e352-4659-851a-f36106186a9a")
                        },
                        new
                        {
                            GenreId = new Guid("16f86a14-951e-4d5d-a8a2-1b851bfedbf0"),
                            BookId = new Guid("eb8227df-e352-4659-851a-f36106186a9a")
                        },
                        new
                        {
                            GenreId = new Guid("2407f9f6-9366-44cc-a778-a6542fbf117d"),
                            BookId = new Guid("86b2636c-0f1c-44f8-ade9-e9437f5bd1da")
                        },
                        new
                        {
                            GenreId = new Guid("3af32f58-6e4f-4cda-8ab5-e2a3c2930109"),
                            BookId = new Guid("8cb48997-f476-4cfc-9ef2-ef89af50fd3c")
                        },
                        new
                        {
                            GenreId = new Guid("2407f9f6-9366-44cc-a778-a6542fbf117d"),
                            BookId = new Guid("ef708df4-7cc7-4b5f-8b78-6c5104f8e100")
                        },
                        new
                        {
                            GenreId = new Guid("6fdde76f-4321-4d4a-a7ed-83ed682a6d62"),
                            BookId = new Guid("ef708df4-7cc7-4b5f-8b78-6c5104f8e100")
                        },
                        new
                        {
                            GenreId = new Guid("3e9f2549-c5f1-49bc-a5c7-642104b6321e"),
                            BookId = new Guid("fbaad571-7547-4f12-8541-ff4c011d6482")
                        },
                        new
                        {
                            GenreId = new Guid("1f7e00a3-33bc-40e3-86cb-0cc3d5960bd9"),
                            BookId = new Guid("fbaad571-7547-4f12-8541-ff4c011d6482")
                        },
                        new
                        {
                            GenreId = new Guid("3e9f2549-c5f1-49bc-a5c7-642104b6321e"),
                            BookId = new Guid("41dd2dd8-7c58-4ab8-9ea1-b35c57366080")
                        },
                        new
                        {
                            GenreId = new Guid("3e9f2549-c5f1-49bc-a5c7-642104b6321e"),
                            BookId = new Guid("9cece5b1-d2c5-4f34-a19f-54ee61b76b47")
                        },
                        new
                        {
                            GenreId = new Guid("a4adf827-2747-40d7-801b-07115f9f0082"),
                            BookId = new Guid("9cece5b1-d2c5-4f34-a19f-54ee61b76b47")
                        },
                        new
                        {
                            GenreId = new Guid("cfc35fd7-ff41-44bb-9779-dc0f98ad8eb2"),
                            BookId = new Guid("9cece5b1-d2c5-4f34-a19f-54ee61b76b47")
                        },
                        new
                        {
                            GenreId = new Guid("0cf8b380-2197-475e-b2a3-58933b2b28da"),
                            BookId = new Guid("529ee040-5ed8-42ed-be65-e05c4be21528")
                        },
                        new
                        {
                            GenreId = new Guid("3552e9af-420f-4ac5-b2a7-1c2df67ea04d"),
                            BookId = new Guid("39c21217-e288-4b21-90da-68dbec7b7e8f")
                        },
                        new
                        {
                            GenreId = new Guid("1f7e00a3-33bc-40e3-86cb-0cc3d5960bd9"),
                            BookId = new Guid("39c21217-e288-4b21-90da-68dbec7b7e8f")
                        },
                        new
                        {
                            GenreId = new Guid("b621b43e-4639-44c1-9a30-9aaa12b2ac80"),
                            BookId = new Guid("fdaff6b9-0881-449f-b921-d9853cd2d725")
                        },
                        new
                        {
                            GenreId = new Guid("5f9b5fb9-506d-4c07-80ef-e5b7fcc3b6f2"),
                            BookId = new Guid("fdaff6b9-0881-449f-b921-d9853cd2d725")
                        },
                        new
                        {
                            GenreId = new Guid("5f9b5fb9-506d-4c07-80ef-e5b7fcc3b6f2"),
                            BookId = new Guid("ea98eb91-35a7-4638-8d81-9df9bcf55e47")
                        },
                        new
                        {
                            GenreId = new Guid("3af32f58-6e4f-4cda-8ab5-e2a3c2930109"),
                            BookId = new Guid("c76dd43e-0e97-4692-84cb-8d4f2b8451df")
                        },
                        new
                        {
                            GenreId = new Guid("ce160fd7-cb8c-4185-99e2-f398e52678cc"),
                            BookId = new Guid("c76dd43e-0e97-4692-84cb-8d4f2b8451df")
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BookHireCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("BookHiredDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("BooksHiresInfos");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BookHireItem", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookHireCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("BookHireExpiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("BookReturnDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsBookReturned")
                        .HasColumnType("bit");

                    b.HasKey("BookId", "BookHireCardId");

                    b.HasIndex("BookHireCardId");

                    b.ToTable("BookHireItems");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e9f2549-c5f1-49bc-a5c7-642104b6321e"),
                            Title = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("3af32f58-6e4f-4cda-8ab5-e2a3c2930109"),
                            Title = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("6fdde76f-4321-4d4a-a7ed-83ed682a6d62"),
                            Title = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("3552e9af-420f-4ac5-b2a7-1c2df67ea04d"),
                            Title = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("a4adf827-2747-40d7-801b-07115f9f0082"),
                            Title = "Romance"
                        },
                        new
                        {
                            Id = new Guid("b621b43e-4639-44c1-9a30-9aaa12b2ac80"),
                            Title = "Historical Fiction"
                        },
                        new
                        {
                            Id = new Guid("1f7e00a3-33bc-40e3-86cb-0cc3d5960bd9"),
                            Title = "Horror"
                        },
                        new
                        {
                            Id = new Guid("ce160fd7-cb8c-4185-99e2-f398e52678cc"),
                            Title = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("16f86a14-951e-4d5d-a8a2-1b851bfedbf0"),
                            Title = "Non-Fiction"
                        },
                        new
                        {
                            Id = new Guid("600d8d8a-a57a-4fa9-83ec-40fa7ebe45ba"),
                            Title = "Biography"
                        },
                        new
                        {
                            Id = new Guid("5f9b5fb9-506d-4c07-80ef-e5b7fcc3b6f2"),
                            Title = "Drama"
                        },
                        new
                        {
                            Id = new Guid("4d56568a-f1f7-46a0-b2aa-a5cf89f033f3"),
                            Title = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("bc6621c3-2a57-4271-8820-93d94501eeba"),
                            Title = "Poetry"
                        },
                        new
                        {
                            Id = new Guid("0cf8b380-2197-475e-b2a3-58933b2b28da"),
                            Title = "Self-Help"
                        },
                        new
                        {
                            Id = new Guid("2407f9f6-9366-44cc-a778-a6542fbf117d"),
                            Title = "Cookbook"
                        },
                        new
                        {
                            Id = new Guid("e0be5314-1296-4988-b09f-11fca7c85060"),
                            Title = "Science"
                        },
                        new
                        {
                            Id = new Guid("cfc35fd7-ff41-44bb-9779-dc0f98ad8eb2"),
                            Title = "Business"
                        },
                        new
                        {
                            Id = new Guid("c9669d77-fef5-4096-af97-5cf06e75feb3"),
                            Title = "Travel"
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Book", b =>
                {
                    b.HasOne("TestTask.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BookGenre", b =>
                {
                    b.HasOne("TestTask.Domain.Entities.Book", "Book")
                        .WithMany("Genres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTask.Domain.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BookHireItem", b =>
                {
                    b.HasOne("TestTask.Domain.Entities.BookHireCard", "BookHireCard")
                        .WithMany("Books")
                        .HasForeignKey("BookHireCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTask.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookHireCard");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Book", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.BookHireCard", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
